"""empty message

Revision ID: 4d0140a1d8a0
Revises: 8e7a97f822be
Create Date: 2024-05-10 13:48:30.391933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0140a1d8a0'
down_revision = '8e7a97f822be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descript', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('descript')

    # ### end Alembic commands ###
