"""empty message

Revision ID: 8e7a97f822be
Revises: e34df954f380
Create Date: 2024-05-10 12:49:14.461688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e7a97f822be'
down_revision = 'e34df954f380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('descript')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descript', mysql.VARCHAR(length=300), nullable=True))

    # ### end Alembic commands ###
