"""empty message

Revision ID: e85e89c45de4
Revises: 2de6b72eb429
Create Date: 2024-04-28 15:52:03.875650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e85e89c45de4'
down_revision = '2de6b72eb429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descript', sa.String(length=300), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('descript')

    # ### end Alembic commands ###
