# Generated by Django 4.2.6 on 2023-10-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя заказчика', max_length=50, verbose_name='Имя заказчика')),
                ('last_name', models.CharField(help_text='Введите фамилию заказчика', max_length=50, verbose_name='Фамилия заказчика')),
                ('address', models.CharField(help_text='Введите адрес', max_length=100, verbose_name='Адрес')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.SlugField(help_text='Введите название модели', verbose_name='Название модели')),
                ('diagonal', models.IntegerField(help_text='Введите размер диагонали', verbose_name='Размер диагонали')),
                ('color', models.CharField(help_text='Введите цвет модели', max_length=50, verbose_name='Цвет')),
            ],
            options={
                'db_table': 'Monitor',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Введите имя поставщика', max_length=50, null=True, verbose_name='Имя поставщика')),
                ('last_name', models.CharField(blank=True, help_text='Введите фамилию поставщика', max_length=50, null=True, verbose_name='Фамилия поставщика')),
            ],
            options={
                'db_table': 'Provider',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Введите количество', verbose_name='Количество')),
                ('order_date', models.DateField(help_text='Введите предположительную дату получения заказа', verbose_name='Дата получения')),
                ('customer', models.ForeignKey(help_text='Выберите заказчика', on_delete=django.db.models.deletion.CASCADE, to='myProject.customer', verbose_name='Заказчик')),
                ('monitor', models.ForeignKey(help_text='Выберите название монитора', on_delete=django.db.models.deletion.CASCADE, to='myProject.monitor', verbose_name='Монитор')),
                ('provider', models.ForeignKey(help_text='Выберите поставщика', on_delete=django.db.models.deletion.CASCADE, to='myProject.provider', verbose_name='Поставщик')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
