# Generated by Django 4.2.6 on 2023-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0002_order_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='store',
            field=models.CharField(blank=True, help_text='Введите адрес склада', max_length=50, null=True, verbose_name='Склад'),
        ),
    ]
