# Generated by Django 4.2.6 on 2023-10-11 12:33

from django.db import migrations
import myProject.models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0002_customer_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=myProject.models.IntegerRangeField(default=1, help_text='Введите номер заказа', verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
