# Generated by Django 4.2.6 on 2023-12-13 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myProject.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myProject', '0003_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='id_user',
            field=models.ForeignKey(blank=True, help_text='Выберите id пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myProject.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myProject.monitor', verbose_name='Монитор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=myProject.models.IntegerRangeField(verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myProject.provider', verbose_name='Поставщик'),
        ),
    ]
