# Generated by Django 4.2.6 on 2023-12-14 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0004_provider_id_user_alter_order_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor', models.ManyToManyField(to='myProject.monitor')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myProject.provider', verbose_name='Поставщик')),
            ],
            options={
                'db_table': 'Statistics',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='statistics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myProject.statistics', verbose_name='Статистика'),
        ),
    ]
