# Generated by Django 4.2.6 on 2023-12-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0005_statistics_order_statistics'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statistics',
            table=None,
        ),
    ]
