# Generated by Django 4.2.6 on 2023-12-14 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0006_alter_statistics_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statistics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myProject.statistics', verbose_name='Статистика'),
        ),
    ]
