# Generated by Django 4.2.6 on 2023-12-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0007_alter_order_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statistics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myProject.statistics', verbose_name='Статистика'),
        ),
        migrations.AlterModelTable(
            name='statistics',
            table='Statistics',
        ),
    ]
