# Generated by Django 4.2.6 on 2023-12-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0008_alter_order_statistics_alter_statistics_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statistics',
            table=None,
        ),
    ]
