# Generated by Django 4.2.6 on 2023-12-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0009_alter_statistics_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='region',
            field=models.CharField(blank=True, help_text='Введите регион поставки', max_length=50, null=True, verbose_name='Регион поставки'),
        ),
    ]
