"""Second migration.

Revision ID: ce8617cc901d
Revises: a51ddb845bb3
Create Date: 2024-03-16 20:09:25.607478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8617cc901d'
down_revision = 'a51ddb845bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
